on:
  issues:
    types: [opened, edited]

name: Auto-Assign Workflow

jobs:
  assignAuthor:
    name: Assign author to issue
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      - uses: technote-space/assign-author@gh-actions
            
