name: Auto-label Issues

on:
  issues:
    types: [opened, edited]

jobs:
  labeler:
    runs-on: ubuntu-latest
    steps:
      - name: Label issues based on title
        uses: actions/github-script@v6
        with:
          script: |
            const issueTitle = context.payload.issue.title.toLowerCase();
            const issueNumber = context.payload.issue.number;
            const labelsToAdd = [];

            // Define labeling rules based on title content
            if (issueTitle.includes('Best Practice')) {
              labelsToAdd.push('BEST PRACTICE');
            }
            if (issueTitle.includes('Checklist')) {
              labelsToAdd.push('CHECKLIST');
            }
            if (issueTitle.includes('Diagram')) {
              labelsToAdd.push('DIAGRAM');
            }
            if (issueTitle.includes('Guideline')) {
              labelsToAdd.push('GUIDELINE');
            }
            if (issueTitle.includes('Policy')) {
              labelsToAdd.push('POLICY');
            }
            if (issueTitle.includes('Procedure')) {
              labelsToAdd.push('PROCEDURE');
            }
            if (issueTitle.includes('Standard')) {
              labelsToAdd.push('STANDARD');
            }

            // Add labels to the issue
            if (labelsToAdd.length > 0) {
              await github.issues.addLabels({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: issueNumber,
                labels: labelsToAdd
              });
            }
